# Generated by Django 4.1.10 on 2023-08-12 18:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCollegeDetailModel',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enrollmentNumber', models.CharField(max_length=15)),
                ('college', models.CharField(max_length=15)),
                ('branch', models.CharField(max_length=15)),
                ('passingYear', models.IntegerField()),
                ('currentCGPA', models.DecimalField(decimal_places=2, max_digits=3)),
                ('currentBacklog', models.IntegerField()),
                ('totalBacklog', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentPersonalDetailModel',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('whatsappMobile', models.CharField(max_length=50)),
                ('alternateMobile', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('isVerified', models.BooleanField(default=False)),
                ('isBlocked', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSchoolDetailModel',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schoolingMedium', models.CharField(choices=[('GUJ', 'Gujarati'), ('ENG', 'English'), ('HN', 'Hindi')], max_length=50)),
                ('twelvePercent', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('diplomaPercent', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('tenPercent', models.DecimalField(decimal_places=2, max_digits=4)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('studentId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.studentpersonaldetailmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='StudentEducationModel',
        ),
        migrations.DeleteModel(
            name='StudentProfileModel',
        ),
        migrations.AddField(
            model_name='studentcollegedetailmodel',
            name='studentId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.studentpersonaldetailmodel'),
        ),
    ]
