# Generated by Django 4.1.3 on 2023-08-13 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0003_alter_studentcollegedetailmodel_enrollmentnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcollegedetailmodel',
            name='currentBacklog',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='studentcollegedetailmodel',
            name='studentId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentcollegedetailmodel',
            name='totalBacklog',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='studentschooldetailmodel',
            name='studentId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='StudentPersonalDetailModel',
        ),
    ]
