# Generated by Django 4.1.10 on 2023-08-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_studentpersonaldetailmodel_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpersonaldetailmodel',
            name='isBlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentpersonaldetailmodel',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentpersonaldetailmodel',
            name='placementGuidelineForm',
            field=models.FileField(default=None, upload_to='student_placement_guidelines_form/'),
        ),
        migrations.AlterField(
            model_name='studentpersonaldetailmodel',
            name='resume',
            field=models.FileField(upload_to='student_resume/'),
        ),
    ]
