# Generated by Django 4.1.10 on 2023-08-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_studentpersonaldetailmodel_isblocked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpersonaldetailmodel',
            name='placementGuidelineForm',
            field=models.FileField(upload_to='student_placement_guidelines_form/'),
        ),
    ]
