# Generated by Django 4.1.10 on 2023-08-24 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_studentpersonaldetailmodel_placementguidelineform'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpersonaldetailmodel',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentcollegedetailmodel',
            name='studentId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='college_detail', to='students.studentpersonaldetailmodel'),
        ),
        migrations.AlterField(
            model_name='studentschooldetailmodel',
            name='studentId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school_detail', to='students.studentpersonaldetailmodel'),
        ),
    ]
