# Generated by Django 4.1.10 on 2023-08-28 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0009_studentpersonaldetailmodel_iscompleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('whatsappMobile', models.CharField(max_length=150)),
                ('alternateMobile', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('profilePic', models.ImageField(upload_to='student_profile_pic/')),
                ('resume', models.FileField(upload_to='student_resume/')),
                ('placementGuidelineForm', models.FileField(upload_to='student_placement_guidelines_form/')),
                ('schoolMedium', models.CharField(choices=[('GUJ', 'Gujarati'), ('ENG', 'English'), ('HN', 'Hindi')], max_length=50)),
                ('twelvePercent', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('diplomaPercent', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('tenPercent', models.DecimalField(decimal_places=2, max_digits=4)),
                ('enrollmentNumber', models.CharField(max_length=15, unique=True)),
                ('college', models.CharField(max_length=15)),
                ('branch', models.CharField(max_length=15)),
                ('passingYear', models.IntegerField()),
                ('currentCGPA', models.DecimalField(decimal_places=2, max_digits=3)),
                ('currentBacklog', models.IntegerField(blank=True, default=None, null=True)),
                ('totalBacklog', models.IntegerField(blank=True, default=None, null=True)),
                ('isCompleted', models.BooleanField(default=False)),
                ('isVerified', models.BooleanField(default=False)),
                ('isBlocked', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('studentId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='studentDetail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentpersonaldetailmodel',
            name='studentId',
        ),
        migrations.RemoveField(
            model_name='studentschooldetailmodel',
            name='studentId',
        ),
        migrations.DeleteModel(
            name='StudentCollegeDetailModel',
        ),
        migrations.DeleteModel(
            name='StudentPersonalDetailModel',
        ),
        migrations.DeleteModel(
            name='StudentSchoolDetailModel',
        ),
    ]
