# Generated by Django 4.1.10 on 2023-09-11 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_studentmodel_and_more'),
        ('placement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementapplicationmodel',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('interviewed', 'Interviewed'), ('placed', 'Placed')], default='appliedCompany', max_length=20),
        ),
        migrations.AlterField(
            model_name='placementapplicationmodel',
            name='studentId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appliedStudent', to='students.studentmodel'),
        ),
    ]
