# Generated by Django 4.1.10 on 2023-09-13 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_studentmodel_and_more'),
        ('placement', '0003_alter_placementapplicationmodel_companyid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementapplicationmodel',
            name='studentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appliedStudent', to='students.studentmodel'),
        ),
    ]
