# Generated by Django 4.1.10 on 2023-09-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_rename_facultypersonalmodel_facultymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultymodel',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
