# Generated by Django 4.1.10 on 2023-08-12 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentEducationModel',
        ),
        migrations.DeleteModel(
            name='StudentProfileModel',
        ),
    ]
