# Generated by Django 4.1.3 on 2023-08-13 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentmodel',
            options={},
        ),
        migrations.AlterModelManagers(
            name='studentmodel',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='user_permissions',
        ),
    ]
