# Generated by Django 4.1.10 on 2023-08-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_studentmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='password',
            field=models.CharField(max_length=150),
        ),
    ]
