# Generated by Django 4.1.10 on 2023-08-19 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customusermodel_delete_facultymodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customusermodel',
            old_name='isFaculty',
            new_name='isStaff',
        ),
        migrations.RemoveField(
            model_name='customusermodel',
            name='isBlocked',
        ),
        migrations.RemoveField(
            model_name='customusermodel',
            name='isVerified',
        ),
    ]
